#!/bin/bash -xe

. ./hooks/env

case "${DOCKER_TAG}" in
    latest)
        docker tag $IMAGE_NAME $DOCKER_REPO:$ARCHIVE_TAG
        docker push $DOCKER_REPO:$ARCHIVE_TAG
        ;;
    firefox)
        docker tag $IMAGE_NAME $DOCKER_REPO:$ARCHIVE_TAG_FIREFOX
        docker push $DOCKER_REPO:$ARCHIVE_TAG_FIREFOX
        ;;
    chromium)
        docker tag $IMAGE_NAME $DOCKER_REPO:$ARCHIVE_TAG_CHROMIUM
        docker push $DOCKER_REPO:$ARCHIVE_TAG_CHROMIUM
        ;;
esac
