# docker build -f Dockerfile.firefox.plus -t accetto/xubuntu-vnc-firefox:myown .

ARG BASETAG=latest

FROM accetto/xubuntu-vnc-firefox:${BASETAG}

USER 0

COPY [ "./src/firefox.plus/user.js", "${HOME}/firefox.plus/user.js" ]

RUN ${STARTUPDIR}/set_user_permissions.sh "${HOME}/firefox.plus"

ENV REFRESHED_AT 2019-07-13

USER 1001
