# ./hooks/build dev
# ./hooks/test dev

### Example: Build and test 'dev' tag locally like
### ./hooks/build dev
### ./hooks/test dev
### or with additional arguments
### ./hooks/build dev --no-cache
### ./hooks/test dev
### or using the utility
### ./utils/util-hdx.sh Dockerfile 1
### ./utils/util-hdx.sh Dockerfile 2
### The last output line should be '+ exit 0'
### If '+ exit 1' then adjust the version sticker
### variables in script './hooks/env'

ARG BASEIMAGE=accetto/xubuntu-vnc
ARG BASETAG=latest

FROM ${BASEIMAGE}:${BASETAG} as stage-drawio
ARG ARG_DRAWIO_VERSION

### Switch to root user before install
USER 0

### also fixing the bug in the package 14.4.3 (https://github.com/jgraph/drawio-desktop/issues/519)
RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
        xdg-utils \
        libappindicator3-1 \
    && DRAWIO_VERSION="${ARG_DRAWIO_VERSION}" \
    && wget -q "https://github.com/jgraph/drawio-desktop/releases/download/v${DRAWIO_VERSION}/draw.io-amd64-${DRAWIO_VERSION}.deb" \
        && dpkg -i draw.io-amd64-${DRAWIO_VERSION}.deb \
        && apt-get -y -f install \
        && rm draw.io-amd64-${DRAWIO_VERSION}.deb \
        && rm -f /usr/bin/drawio \
        && ln -s /opt/draw.io/drawio /usr/bin/drawio \
    && apt-get -y autoremove \
    && rm -rf /var/lib/apt/lists/*

### Preconfigure Xfce 
COPY [ "./src/home/Desktop", "${HOME}/Desktop/" ]
COPY [ "./src/startup/version_sticker.sh", "${STARTUPDIR}/" ]
COPY [ "./src/home/Desktop/drawio.desktop", "/usr/share/applications/drawio.desktop" ]

### Fix permissions
RUN \
    chmod a+wx "${STARTUPDIR}"/version_sticker.sh \
    && "${STARTUPDIR}"/set_user_permissions.sh "${STARTUPDIR}" "${HOME}"

FROM stage-drawio as stage-final

ARG ARG_REFRESHED_AT
ARG ARG_VERSION_STICKER
ARG ARG_VCS_REF

LABEL \
    org.label-schema.vcs-ref="${ARG_VCS_REF}" \
    version-sticker="${ARG_VERSION_STICKER}"

ENV \
    REFRESHED_AT=${ARG_REFRESHED_AT} \
    VERSION_STICKER=${ARG_VERSION_STICKER}

### Switch to default application user (non-root)
USER 1001
